# Generated by Django 4.1.3 on 2022-11-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(default=1, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
