# Generated by Django 4.1.3 on 2022-11-23 14:20

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[core.validators.validate_file_max_size_in_mb]),
        ),
    ]
